# Generated by Django 4.2.2 on 2023-06-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='fname',
            field=models.CharField(default='maria ', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='lname',
            field=models.CharField(default='valencia', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='document_type',
            field=models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('PPT', 'permiso de protección temporal'), ('CE', 'Cedula de extranjería'), ('TI', 'Tarjeta de identidad')], default='cc', max_length=3),
        ),
    ]
